name: Build

on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: jossef/action-set-json-field@v1
              with:
                  file: package.json
                  field: version
                  value: ${{ github.run_number }}.0.0
            - uses: jossef/action-set-json-field@v1
              with:
                  file: public/manifest.json
                  field: version
                  value: ${{ github.run_number }}.0.0
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - run: npm install
            - run: npm run build
            - uses: actions/upload-artifact@v1
              with:
                  name: stream-together-web-extension
                  path: dist/
